trigger:
- main
- feature\*

pool: infra_dondu

parameters:
  - name: tfsec
    displayName: tfsec krna hai?
    type: boolean
    default: false

  - name: tflint
    displayName: tflint krna hai?
    type: boolean
    default: false

stages:
  - stage: tfsec
    dependsOn: []
    condition: ${{ parameters.tfsec }}
    displayName: tfsec scan
    jobs:
      - job: tfsec
        displayName: tfsec scan
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'tfsec'

  - stage: tflint
    dependsOn: []
    condition: ${{ parameters.tflint }}
    displayName: tflint scan
    jobs:
      - job: tflint
        displayName: tflint scan
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'tflint --recursive --force'

  - stage: init
    dependsOn:
    - tfsec
    - tflint
    displayName: init
    jobs:
      - job: init
        displayName: init
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'Dondu_Service_Connection'
              backendAzureRmStorageAccountName: 'dondu'
              backendAzureRmContainerName: 'dondustorage'
              backendAzureRmKey: 'lab.tfstate'

  - stage: validate
    dependsOn:
    - init
    displayName: validate
    jobs:
      - job: validate
        displayName: validate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'Dondu_Service_Connection'
              backendAzureRmStorageAccountName: 'dondu'
              backendAzureRmContainerName: 'dondustorage'
              backendAzureRmKey: 'lab.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'

  - stage: plan
    dependsOn:
    - validate
    displayName: plan
    jobs:
      - job: plan
        displayName: plan
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'Dondu_Service_Connection'
              backendAzureRmStorageAccountName: 'dondu'
              backendAzureRmContainerName: 'dondustorage'
              backendAzureRmKey: 'lab.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Dondu_Service_Connection'

  - stage: approval
    dependsOn:
    - plan
    displayName: approval
    jobs:
      - job: approval
        displayName: approval
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'abc'
          
  - stage: apply
    dependsOn:
    - approval
    displayName: apply
    jobs:
      - job: apply
        displayName: apply
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'Dondu_Service_Connection'
              backendAzureRmStorageAccountName: 'dondu'
              backendAzureRmContainerName: 'dondustorage'
              backendAzureRmKey: 'lab.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Dondu_Service_Connection'
          