trigger:
  - main
  - feature

pool: infra_dondu

parameters:
  - name: tfsec
    displayName: tfsec chalana hai kya?
    type: boolean
    default: false

  - name: tflint
    displayName: tflint chalana hai kya?
    type: boolean
    default: false



stages:
  - stage: tfsec
    dependsOn: []
    condition: ${{ parameters.tfsec }}
    displayName: tfsec Scan
    jobs:
      - job: tfsec
        displayName: tfsec Scan
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'tfsec'

  - stage: tflint
    dependsOn: []
    condition: ${{ parameters.tflint }}
    displayName: tflint Scan
    jobs:
      - job: tflint
        displayName: tflint scan
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'tflint --recursive --force'

  - stage: init
    dependsOn:
    - tfsec
    - tflint
    displayName: init and validate
    jobs:
      - job: init
        displayName: init and validate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'Dondu_Service_Connection'
              backendAzureRmStorageAccountName: 'dondustorage'
              backendAzureRmContainerName: 'bopu'
              backendAzureRmKey: 'rahul.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'

  - stage: plan
    dependsOn:
    - init
    displayName: plan
    jobs:
      - job: plan
        displayName: plan
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'Dondu_Service_Connection'
              backendAzureRmStorageAccountName: 'dondustorage'
              backendAzureRmContainerName: 'bopu'
              backendAzureRmKey: 'rahul.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Dondu_Service_Connection'

  - stage: approval
    dependsOn:
    - init
    - plan

    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    displayName: approval
    jobs:
      - job: approval
        displayName: approval
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'abc'

  - stage: apply
    dependsOn: approval
    displayName: apply
    jobs:
      - job: apply
        displayName: apply
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'Dondu_Service_Connection'
              backendAzureRmStorageAccountName: 'dondustorage'
              backendAzureRmContainerName: 'bopu'
              backendAzureRmKey: 'rahul.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Dondu_Service_Connection'
          

        
          
